dependencies:
  - name: postgresql
    version: 7.x.x
    tags:
    - postgresql-database
    repository: https://raw.githubusercontent.com/olmax99/treesnqsweb/master/helmdist
    alias: postgresql
    condition: postgresql.enabled
